a = 12
b = 13
puts "a == b >> #{a == b}" 
puts "a != b >> #{a != b}"
puts "a < b  >> #{a < b}"
puts "a <=> b >> #{a <=> b}"
puts "a === b >> #{a === b}"
puts "(1 ... 20) === b >> #{(1...20) === b}"
puts "a.equ?b >> #{a .eql? b}"
puts "a.equ?b >> #{a .equal? b}"
puts "a.equ?a >> #{a .eql? a}"
puts "a >> #{a. to_s 2}"
puts "b >> #{b. to_s 2}"
puts "a&b >> #{(a&b). to_s 2}"
puts "a|b >> #{(a|b). to_s 2}"
puts "a^b >> #{(a^b). to_s 2}"
puts "~a >> #{(~a).to_s 2}"
puts "(a&b) >> 1 >> #{((a&b) >> 1). to_s 2}"
puts "(a&b) << 1 >> #{((a&b) << 1). to_s 2}"
puts "a and b >> #{a and b}"
puts "a definede >> #{defined?a}"